"""Users.id as BIGINT identity (auto-increment); FK columns updated.

Revision ID: 022
Revises: 021
"""

from typing import Sequence, Union

from alembic import op

revision: str = "022"
down_revision: Union[str, None] = "021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop FKs and dependent indexes referencing users.id (PostgreSQL).
    op.execute("ALTER TABLE tenant_memberships DROP CONSTRAINT IF EXISTS uq_tenant_memberships_user_tenant")
    op.execute("ALTER TABLE tenant_memberships DROP CONSTRAINT IF EXISTS tenant_memberships_user_id_fkey")
    op.execute("DROP INDEX IF EXISTS ux_user_llm_prompt_owner")
    op.execute("DROP INDEX IF EXISTS ux_user_llm_prompt_anon")
    op.execute("ALTER TABLE user_llm_prompt_overrides DROP CONSTRAINT IF EXISTS user_llm_prompt_overrides_user_id_fkey")
    op.execute("ALTER TABLE user_narration_styles DROP CONSTRAINT IF EXISTS user_narration_styles_user_id_fkey")
    op.execute("ALTER TABLE agent_runs DROP CONSTRAINT IF EXISTS fk_agent_runs_started_by_user_id_users")
    op.execute("ALTER TABLE music_beds DROP CONSTRAINT IF EXISTS music_beds_uploaded_by_user_id_fkey")

    op.execute("ALTER TABLE users RENAME TO users_uuid_legacy")
    # Index names are schema-global; keep the legacy unique index but rename it so the new `users` table can use `ix_users_email`.
    op.execute("ALTER INDEX IF EXISTS ix_users_email RENAME TO ix_users_uuid_legacy_email")

    op.execute(
        """
        CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR(320) NOT NULL,
            password_hash VARCHAR(256),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE UNIQUE INDEX ix_users_email ON users (email)")

    op.execute(
        """
        INSERT INTO users (email, password_hash, created_at)
        SELECT email, password_hash, created_at FROM users_uuid_legacy
        ORDER BY created_at ASC NULLS LAST, email ASC
        """
    )

    op.execute(
        """
        CREATE TABLE _user_uuid_to_int (
            old_id UUID PRIMARY KEY,
            new_id BIGINT NOT NULL UNIQUE
        )
        """
    )
    op.execute(
        """
        INSERT INTO _user_uuid_to_int (old_id, new_id)
        SELECT u.id, n.id
        FROM users_uuid_legacy u
        INNER JOIN users n ON n.email = u.email AND n.created_at = u.created_at
        """
    )

    # tenant_memberships.user_id
    op.execute("ALTER TABLE tenant_memberships ADD COLUMN user_id_new BIGINT")
    op.execute(
        """
        UPDATE tenant_memberships tm
        SET user_id_new = m.new_id
        FROM _user_uuid_to_int m
        WHERE tm.user_id = m.old_id
        """
    )
    op.execute("ALTER TABLE tenant_memberships DROP COLUMN user_id")
    op.execute("ALTER TABLE tenant_memberships RENAME COLUMN user_id_new TO user_id")
    op.execute("ALTER TABLE tenant_memberships ALTER COLUMN user_id SET NOT NULL")

    # user_llm_prompt_overrides.user_id (nullable)
    op.execute("ALTER TABLE user_llm_prompt_overrides ADD COLUMN user_id_new BIGINT")
    op.execute(
        """
        UPDATE user_llm_prompt_overrides o
        SET user_id_new = m.new_id
        FROM _user_uuid_to_int m
        WHERE o.user_id = m.old_id
        """
    )
    op.execute("ALTER TABLE user_llm_prompt_overrides DROP COLUMN user_id")
    op.execute("ALTER TABLE user_llm_prompt_overrides RENAME COLUMN user_id_new TO user_id")

    # user_narration_styles.user_id (nullable)
    op.execute("ALTER TABLE user_narration_styles ADD COLUMN user_id_new BIGINT")
    op.execute(
        """
        UPDATE user_narration_styles o
        SET user_id_new = m.new_id
        FROM _user_uuid_to_int m
        WHERE o.user_id = m.old_id
        """
    )
    op.execute("ALTER TABLE user_narration_styles DROP COLUMN user_id")
    op.execute("ALTER TABLE user_narration_styles RENAME COLUMN user_id_new TO user_id")

    # agent_runs.started_by_user_id (nullable)
    op.execute("ALTER TABLE agent_runs ADD COLUMN started_by_user_id_new BIGINT")
    op.execute(
        """
        UPDATE agent_runs r
        SET started_by_user_id_new = m.new_id
        FROM _user_uuid_to_int m
        WHERE r.started_by_user_id = m.old_id
        """
    )
    op.execute("ALTER TABLE agent_runs DROP COLUMN started_by_user_id")
    op.execute("ALTER TABLE agent_runs RENAME COLUMN started_by_user_id_new TO started_by_user_id")

    # music_beds.uploaded_by_user_id (nullable)
    op.execute("ALTER TABLE music_beds ADD COLUMN uploaded_by_user_id_new BIGINT")
    op.execute(
        """
        UPDATE music_beds b
        SET uploaded_by_user_id_new = m.new_id
        FROM _user_uuid_to_int m
        WHERE b.uploaded_by_user_id = m.old_id
        """
    )
    op.execute("ALTER TABLE music_beds DROP COLUMN uploaded_by_user_id")
    op.execute("ALTER TABLE music_beds RENAME COLUMN uploaded_by_user_id_new TO uploaded_by_user_id")

    op.execute("DROP TABLE users_uuid_legacy")
    op.execute("DROP TABLE _user_uuid_to_int")

    op.execute(
        """
        ALTER TABLE tenant_memberships
        ADD CONSTRAINT tenant_memberships_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        """
    )
    op.execute(
        """
        ALTER TABLE user_llm_prompt_overrides
        ADD CONSTRAINT user_llm_prompt_overrides_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        """
    )
    op.execute(
        """
        ALTER TABLE user_narration_styles
        ADD CONSTRAINT user_narration_styles_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
        """
    )
    op.execute(
        """
        ALTER TABLE agent_runs
        ADD CONSTRAINT fk_agent_runs_started_by_user_id_users
        FOREIGN KEY (started_by_user_id) REFERENCES users(id) ON DELETE SET NULL
        """
    )
    op.execute(
        """
        ALTER TABLE music_beds
        ADD CONSTRAINT music_beds_uploaded_by_user_id_fkey
        FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id) ON DELETE SET NULL
        """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX ux_user_llm_prompt_owner ON user_llm_prompt_overrides (tenant_id, user_id, prompt_key)
        WHERE user_id IS NOT NULL
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX ux_user_llm_prompt_anon ON user_llm_prompt_overrides (tenant_id, prompt_key)
        WHERE user_id IS NULL
        """
    )
    op.execute(
        "ALTER TABLE tenant_memberships ADD CONSTRAINT uq_tenant_memberships_user_tenant UNIQUE (user_id, tenant_id)"
    )

    op.execute(
        "SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1))"
    )


def downgrade() -> None:
    raise NotImplementedError("Cannot restore UUID user ids after 022")
